name: Build

on:
  push:
    branches: [ main, master ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build (.geode)
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Geode CLI
        run: cargo install --git https://github.com/geode-sdk/cli --locked

      - name: Prepare Geode SDK (Windows)
        if: startsWith(runner.os, 'Windows')
        run: |
          $profilePath = "$env:RUNNER_TEMP\geode-profile"
          New-Item -ItemType Directory -Force -Path $profilePath | Out-Null
          geode profile add --name ci $profilePath windows
          geode profile switch ci
          $env:GEODE_SDK = "$env:GITHUB_WORKSPACE/.geode-sdk"
          geode sdk install "$env:GEODE_SDK" --force
          geode sdk set-path "$env:GEODE_SDK"
          geode sdk install-binaries --platform windows -v 4.7.0
          "GEODE_SDK=$env:GEODE_SDK" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Build (Release)
        run: geode build --config Release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: gd-noclip-${{ runner.os }}
          path: dist/*.geode
