name: Build

on:
  push:
    branches: [ main, master ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build (.geode)
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Geode CLI
        run: cargo install --git https://github.com/geode-sdk/cli --locked

      - name: Build (Release)
        run: geode build --config Release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: gd-noclip-${{ runner.os }}
          path: dist/*.geode
